exports.seed = async function(knex) {
  await knex('tariffs').del();

  await knex('tariffs').insert([
    {
      code: 'pickup_order',
      name: 'Приемка товара — Забор груза',
      description: 'Организация забора груза от клиента или перевозчика до склада фулфилмента',
      unit: 'per_order',
      price: 3000.00,
    },
    {
      code: 'unloading_boxes',
      name: 'Приемка товара — Разгрузка товара на складе ФФ',
      description: 'Разгрузка коробов и размещение на приемке',
      unit: 'per_order',
      price: 30.00,
    },
    {
      code: 'remove_outer_packaging',
      name: 'Приемка товара — Снятие мешков, пакетов, скотча и др. упаковки',
      description: 'Снятие транспортной упаковки и подготовка товара к приемке',
      unit: 'per_order',
      price: 100.00,
    },
    {
      code: 'receiving_per_unit',
      name: 'Приемка товара — Принятие поставки на склад',
      description: 'Поштучная приемка, пересчет и заведение в складской учет',
      unit: 'per_unit',
      price: 6.00,
    },
    {
      code: 'manual_barcoding',
      name: 'Обработка товара — Штрихкодирование товара',
      description: 'Наклейка штрихкода, стикера маркетплейса или внутреннего кода',
      unit: 'per_unit',
      price: 6.00,
    },
    {
      code: 'box_split_mix',
      name: 'Обработка товара — Распределение по коробам (микс)',
      description: 'Распределение ассортимента по коробам с миксом SKU',
      unit: 'per_order',
      price: 70.00,
    },
    {
      code: 'manual_box_604040',
      name: 'Обработка товара — Короб 60/40/40',
      description: 'Сборка и подготовка крупного транспортного короба 60x40x40',
      unit: 'per_order',
      price: 150.00,
    },
    {
      code: 'prep_for_shipment',
      name: 'Обработка товара — Подготовка к поставке',
      description: 'Проверка, консолидация и подготовка партии к отгрузке',
      unit: 'per_order',
      price: 25.00,
    },
    {
      code: 'manual_defect_check',
      name: 'Обработка товара — Проверка на брак',
      description: 'Ручной осмотр товара на повреждения и комплектность',
      unit: 'per_unit',
      price: 25.00,
    },
    {
      code: 'manual_bopp_pack',
      name: 'Обработка товара — Упаковка в БОПП',
      description: 'Упаковка единицы товара в БОПП-пакет',
      unit: 'per_unit',
      price: 25.00,
    },
    {
      code: 'manual_zip_pack',
      name: 'Обработка товара — Упаковка в zip-lock пакет',
      description: 'Упаковка мелких и сыпучих позиций в zip-lock пакет',
      unit: 'per_unit',
      price: 8.00,
    },
    {
      code: 'manual_sticker',
      name: 'Обработка товара — Стикеровка',
      description: 'Наклейка служебных и маркетплейсных стикеров',
      unit: 'per_unit',
      price: 3.00,
    },
    {
      code: 'manual_honest_sign',
      name: 'Обработка товара — Маркировка Честный Знак',
      description: 'Нанесение и проверка кодов Честный Знак',
      unit: 'per_unit',
      price: 8.00,
    },
    {
      code: 'manual_photo_defect',
      name: 'Обработка товара — Фотофиксация брака',
      description: 'Фиксация дефекта с фотоотчетом и привязкой к заявке',
      unit: 'per_unit',
      price: 10.00,
    },
    {
      code: 'manual_monopallet',
      name: 'Обработка товара — Формирование монопаллеты',
      description: 'Подготовка и обвязка монопаллеты под отгрузку',
      unit: 'per_order',
      price: 350.00,
    },
    {
      code: 'manual_stretch_pallet',
      name: 'Обработка товара — Стретч-упаковка паллеты',
      description: 'Обмотка паллеты стрейч-пленкой и фиксация груза',
      unit: 'per_order',
      price: 150.00,
    },
    {
      code: 'storage_per_unit_day',
      name: 'Хранение (бесплатное)',
      description: 'Базовое бесплатное хранение в рамках тарифа',
      unit: 'per_day',
      price: 0.00,
    },
    {
      code: 'storage_paid_per_unit_day',
      name: 'Хранение (платное)',
      description: 'Платное хранение единицы товара за день',
      unit: 'per_day',
      price: 0.50,
    },
    {
      code: 'logistics_wb_order',
      name: 'Логистика WB — Оформление поставки',
      description: 'Подготовка поставки и оформление документов в Wildberries',
      unit: 'per_order',
      price: 500.00,
    },
    {
      code: 'logistics_wb_tula',
      name: 'Логистика WB — Алексин (Тула)',
      description: 'Доставка и сопровождение поставки до склада WB Алексин',
      unit: 'per_order',
      price: 700.00,
    },
    {
      code: 'logistics_ozon_order',
      name: 'Логистика Ozon — Оформление поставки',
      description: 'Подготовка и оформление поставки в Ozon',
      unit: 'per_order',
      price: 550.00,
    },
    {
      code: 'logistics_yandex_order',
      name: 'Логистика Яндекс.Маркет — Оформление поставки',
      description: 'Подготовка и оформление поставки в Яндекс.Маркет',
      unit: 'per_order',
      price: 550.00,
    },
    {
      code: 'logistics_per_unit',
      name: 'Логистика — За единицу в поставке',
      description: 'Пересчет и обработка каждой единицы при формировании поставки',
      unit: 'per_unit',
      price: 2.00,
    },
    {
      code: 'defect_processing',
      name: 'Обработка брака',
      description: 'Осмотр, фиксация и оформление бракованного товара',
      unit: 'per_unit',
      price: 10.00,
    },
    {
      code: 'receiving_pickup_m3',
      name: 'Приемка товара — Забор груза (ТЯК Москва / ТЦ Садовод / Южные ворота / Карго)',
      description: '2500р/м3; за каждый последующий м3 +1000р; въезд на территорию рынка, стоянка и грузчики оплачиваются отдельно',
      unit: 'per_m3',
      price: 2500.00,
    },
    {
      code: 'receiving_unload_m3',
      name: 'Приемка товара — Разгрузка товара на складе',
      description: '300р/м3; за каждый последующий м3 +300р',
      unit: 'per_m3',
      price: 300.00,
    },
    {
      code: 'receiving_count',
      name: 'Приемка товара — Пересчет товара при приёмке',
      description: '2р/ед; пересчёт - это обязательная услуга при обработке товара',
      unit: 'per_unit',
      price: 2.00,
    },
    {
      code: 'receiving_sort',
      name: 'Приемка товара — Сортировка по видам/цветам/размерам',
      description: '2р/ед; сортировка включается, если у вас более 1 баркода',
      unit: 'per_unit',
      price: 2.00,
    },
    {
      code: 'receiving_ship_m3',
      name: 'Приемка товара — Отгрузка товара со склада (курьер/ТК)',
      description: '300р/м3; за каждый последующий м3 +300р',
      unit: 'per_m3',
      price: 300.00,
    },
    {
      code: 'receiving_photo_video',
      name: 'Приемка товара — Фото/видео отчет при приёмке',
      description: '300р; общий обзор грузовых мест',
      unit: 'per_order',
      price: 300.00,
    },
    {
      code: 'receiving_remove_bracing',
      name: 'Приемка товара — Снятие обрешетки с короба',
      description: '200р/ед',
      unit: 'per_unit',
      price: 200.00,
    },
    {
      code: 'receiving_photo_session',
      name: 'Приемка товара — Подготовка товара на фотосессию + отгрузка / приёмка',
      description: '300р',
      unit: 'per_order',
      price: 300.00,
    },
    {
      code: 'receiving_courier_request',
      name: 'Приемка товара — Оформление заявки на забор груза курьером',
      description: '300р; Яндекс / Достависта / СДЭК / ДЛ',
      unit: 'per_order',
      price: 300.00,
    },
    {
      code: 'receiving_transport_box',
      name: 'Приемка товара — Транспортировочный короб / мешок',
      description: '100р',
      unit: 'per_unit',
      price: 100.00,
    },
    {
      code: 'mark_cross_wb',
      name: 'Обработка товара — Перекрытие ШК ВБ',
      description: '4р/ед',
      unit: 'per_unit',
      price: 4.00,
    },
    {
      code: 'mark_tag_remove',
      name: 'Обработка товара — Снять / навесить бирку',
      description: '5р/ед; пластиковый или веревочный биркодержатель',
      unit: 'per_unit',
      price: 5.00,
    },
    {
      code: 'mark_dummy_tag',
      name: 'Обработка товара — Бирка - пустышка',
      description: '2р/ед; белая бирка с двух сторон',
      unit: 'per_unit',
      price: 2.00,
    },
    {
      code: 'mark_single_label',
      name: 'Обработка товара — Маркировка одинарная',
      description: '7р/этикетка; если одного баркода ШК меньше 10ед, то цена х2',
      unit: 'per_unit',
      price: 7.00,
    },
    {
      code: 'mark_double_label',
      name: 'Обработка товара — Маркировка от 2-х этикеток',
      description: '6р/этикетка; если одного баркода ШК меньше 10ед, то цена х2',
      unit: 'per_unit',
      price: 6.00,
    },
    {
      code: 'mark_chz',
      name: 'Обработка товара — Маркировка ЧЗ',
      description: '7р/этикетка',
      unit: 'per_unit',
      price: 7.00,
    },
    {
      code: 'mark_shk_chz',
      name: 'Обработка товара — Маркировка ШК+ЧЗ',
      description: '10р/этикетка; печать на термотрансферном принтере',
      unit: 'per_unit',
      price: 10.00,
    },
    {
      code: 'pack_after_marking',
      name: 'Обработка товара — Упаковка товара в фабричную упаковку после маркировки',
      description: '5р/ед',
      unit: 'per_unit',
      price: 5.00,
    },
    {
      code: 'insert_leaflet',
      name: 'Обработка товара — Вложение / изъятие вкладыша',
      description: '2р/ед',
      unit: 'per_unit',
      price: 2.00,
    },
    {
      code: 'brand_sticker',
      name: 'Обработка товара — Наклеить наклейку бренда с лого',
      description: '2р/ед',
      unit: 'per_unit',
      price: 2.00,
    },
    {
      code: 'tape_fix',
      name: 'Обработка товара — Фиксация скотчем',
      description: '2р/ед',
      unit: 'per_unit',
      price: 2.00,
    },
    {
      code: 'transparent_sticker_fix',
      name: 'Обработка товара — Фиксация круглой прозрачной этикеткой',
      description: '2р/ед',
      unit: 'per_unit',
      price: 2.00,
    },
    {
      code: 'set_assembly',
      name: 'Обработка товара — Комплектовка / фасовка',
      description: 'от 10р/ед',
      unit: 'per_unit',
      price: 10.00,
    },
    {
      code: 'measure_clothes',
      name: 'Обработка товара — Снятие мерок для одежды (по ТЗ клиента)',
      description: '300р/sku; 6 показателей',
      unit: 'per_unit',
      price: 300.00,
    },
    {
      code: 'measure_dimensions',
      name: 'Обработка товара — Замер габаритов товара (длина, ширина, высота)',
      description: '100р/sku',
      unit: 'per_unit',
      price: 100.00,
    },
    {
      code: 'measure_weight',
      name: 'Обработка товара — Замер веса товара',
      description: '100р/sku',
      unit: 'per_unit',
      price: 100.00,
    },
    {
      code: 'chz_report',
      name: 'Обработка товара — Отчет о наклеенных ЧЗ (по поставке)',
      description: '10р/ед ЧЗ',
      unit: 'per_unit',
      price: 10.00,
    },
    {
      code: 'print_tags_logo',
      name: 'Обработка товара — Печать бирок с ваших логотипом',
      description: 'от 5р/ед',
      unit: 'per_unit',
      price: 5.00,
    },
    {
      code: 'box_assembly_four',
      name: 'Обработка товара — Сборка коробок (четырехклапанная)',
      description: '7р/ед',
      unit: 'per_unit',
      price: 7.00,
    },
    {
      code: 'box_assembly_self',
      name: 'Обработка товара — Сборка коробок (самосборная)',
      description: '12р/ед',
      unit: 'per_unit',
      price: 12.00,
    },
    {
      code: 'box_assembly_lid',
      name: 'Обработка товара — Сборка коробок (коробка-крышка)',
      description: '15р/ед',
      unit: 'per_unit',
      price: 15.00,
    },
    {
      code: 'defect_check_1',
      name: 'Обработка товара — Проверка на брак - 1 уровень',
      description: '8р/ед; стандартный осмотр',
      unit: 'per_unit',
      price: 8.00,
    },
    {
      code: 'defect_check_2',
      name: 'Обработка товара — Проверка на брак - 2 уровень',
      description: '16р/ед; детальная проверка',
      unit: 'per_unit',
      price: 16.00,
    },
    {
      code: 'defect_check_3',
      name: 'Обработка товара — Проверка на брак - 3 уровень',
      description: 'от 24р/ед; проверка по ТЗ клиента',
      unit: 'per_unit',
      price: 24.00,
    },
    {
      code: 'thread_trim_1',
      name: 'Обработка товара — Обрезка ниток - 1 уровень',
      description: '3р/ед; мало ниток (1-3 места)',
      unit: 'per_unit',
      price: 3.00,
    },
    {
      code: 'thread_trim_2',
      name: 'Обработка товара — Обрезка ниток - 2 уровень',
      description: '6р/ед; много ниток (4-6 мест)',
      unit: 'per_unit',
      price: 6.00,
    },
    {
      code: 'thread_trim_3',
      name: 'Обработка товара — Обрезка ниток - 3 уровень',
      description: 'от 10р/ед; очень много ниток / обработка по ТЗ',
      unit: 'per_unit',
      price: 10.00,
    },
    {
      code: 'defect_photo',
      name: 'Обработка товара — Фото брака каждой единицы товара',
      description: '5р/ед',
      unit: 'per_unit',
      price: 5.00,
    },
    {
      code: 'client_repack',
      name: 'Обработка товара — Укладка товара в упаковку клиента после проверки на брак',
      description: '10р/ед',
      unit: 'per_unit',
      price: 10.00,
    },
    {
      code: 'steaming',
      name: 'Обработка товара — Отпаривание',
      description: 'от 60р/ед',
      unit: 'per_unit',
      price: 60.00,
    },
  ]);

  console.log('✅ Тарифы созданы');
};
