exports.seed = async function(knex) {
  await knex('consumables').del();

  await knex('consumables').insert([
    {
      code: 'box_302020',
      name: 'Короб 30x20x20',
      category: 'Коробки',
      unit: 'шт',
      price: 18.00,
      stock_qty: 600,
      min_qty: 100,
      comment: 'Для мелких товаров и компактных отгрузок',
    },
    {
      code: 'box_403030',
      name: 'Короб 40x30x30',
      category: 'Коробки',
      unit: 'шт',
      price: 28.00,
      stock_qty: 420,
      min_qty: 80,
      comment: 'Универсальный короб для поставок на маркетплейсы',
    },
    {
      code: 'box_604040',
      name: 'Короб 60x40x40',
      category: 'Коробки',
      unit: 'шт',
      price: 45.00,
      stock_qty: 180,
      min_qty: 30,
      comment: 'Крупный транспортный короб для объемных поставок',
    },
    {
      code: 'bopp_bag',
      name: 'БОПП пакет',
      category: 'Пакеты',
      unit: 'шт',
      price: 3.00,
      stock_qty: 3000,
      min_qty: 500,
      comment: 'Прозрачный упаковочный пакет для единичной упаковки товара',
    },
    {
      code: 'ziplock_a4',
      name: 'Пакет zip-lock A4',
      category: 'Пакеты',
      unit: 'шт',
      price: 3.00,
      stock_qty: 2000,
      min_qty: 300,
      comment: 'Для мелких деталей, фурнитуры и комплектов',
    },
    {
      code: 'tape_brown',
      name: 'Скотч коричневый 50 м',
      category: 'Упаковка',
      unit: 'рулон',
      price: 55.00,
      stock_qty: 120,
      min_qty: 20,
      comment: 'Для заклейки коробов и вторичной упаковки',
    },
    {
      code: 'stretch_film',
      name: 'Стрейч-плёнка',
      category: 'Упаковка',
      unit: 'рулон',
      price: 320.00,
      stock_qty: 95,
      min_qty: 20,
      comment: 'Для паллетирования и фиксации груза',
    },
    {
      code: 'bubble_wrap',
      name: 'Пузырчатая плёнка',
      category: 'Упаковка',
      unit: 'рулон',
      price: 540.00,
      stock_qty: 64,
      min_qty: 15,
      comment: 'Для хрупких и деликатных товаров',
    },
    {
      code: 'kraft_paper',
      name: 'Крафт-бумага',
      category: 'Упаковка',
      unit: 'рулон',
      price: 210.00,
      stock_qty: 40,
      min_qty: 10,
      comment: 'Для заполнения пустот и защиты вложений',
    },
    {
      code: 'thermal_labels_5840',
      name: 'Термоэтикетки 58x40',
      category: 'Маркировка',
      unit: 'рулон',
      price: 145.00,
      stock_qty: 180,
      min_qty: 40,
      comment: 'Для штрихкодов и служебных стикеров',
    },
    {
      code: 'thermal_labels_100150',
      name: 'Термоэтикетки 100x150',
      category: 'Маркировка',
      unit: 'рулон',
      price: 260.00,
      stock_qty: 90,
      min_qty: 20,
      comment: 'Для транспортных ярлыков и маркировки коробов',
    },
    {
      code: 'euro_pallet',
      name: 'Европаллета',
      category: 'Паллеты',
      unit: 'шт',
      price: 350.00,
      stock_qty: 40,
      min_qty: 8,
      comment: 'Для формирования монопаллет и отгрузки на маркетплейсы',
    },
  ]);

  console.log('✅ Расходники созданы');
};
